/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.editor;

import javax.swing.*;

/**
 *
 * @author HP
 */
public class LoginPanel extends javax.swing.JPanel {

    private JFrame parent;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel( JFrame parent) {
        this.parent = parent;
        initComponents();
    }
    private void initComponents() {
    this.setLayout(null);

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_new = new JButton();


        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Gill Sans Nova", 1, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_new.setText("Register");
        btn_new.setVisible(true);

        btn_login.setText("login");
        btn_login.setVisible(true);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(20,100,200,20);
        add(jLabel2);
        jLabel2.setBounds(20,140,200,20);
        add(jLabel3);
        jLabel3.setBounds(160,40,80,20);
        add(txt_username);
        txt_username.setBounds(90,100,100,20);
        add(txt_password);
        txt_password.setBounds(90,140,100, 20);
        add(btn_login);
        btn_login.setBounds(80,300,90,20);
        add(btn_new);
        btn_new.setBounds(230,300,90,20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        
        User u = Loader.loadUserObject(txt_username.getText());
        if(u != null && u.getPassword().equals(txt_password.getText())){
        
            Editor_MainPanel panel = new Editor_MainPanel(u);
            panel.setSize(400, 400);
            panel.setLocationRelativeTo(null);
            panel.setVisible(true);
            parent.setVisible(false);
        }else{
            txt_password.setText("");
            txt_username.setText("");
            JOptionPane.showMessageDialog(parent, "Benutzername oder Passwort falsch!");
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_new;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
