package Yep;

public enum Instruction {
        CREATEUSER,
        DELETEUSER,
        REQUESTUSER,
        JOINQUEUE,
        UPDATEUSER,
        GETALLCHARS,
        SELCHAR,
        GETCHARS,
        EXAB,
        REQPSTATS,
        CHANGENAME,
        REQNAMEHISTORY,
        RDMCHAR,
        REQGAMEUSER,
        GETSETTINGS,
        SAVESETTINGS,
        GAMESTARTCD,
        GAMEFINISCHED,
        REQPWDHISTORY,
        CHANGEPWD,
        REQFIGHTLOG,
        DC,
}
