/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Yep;

import Character.SettingsMgr;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * @author HP
 */
public class LoginPanel extends javax.swing.JPanel {

    private final JFrame parent;
    private StartMenu menu;

    public StartMenu getMenu() {
        return menu;
    }


    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(JFrame parent) {
        this.parent = parent;
        parent.setCursor(Cursor.HAND_CURSOR);
        parent.setResizable(false);
        parent.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setBackground(Color.DARK_GRAY);
        initComponents();
    }

    private void initComponents() {
        AtomicBoolean updateCurser = new AtomicBoolean(true);
        this.setLayout(null);


        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btn_login = new JButton();
        JButton btn_new = new JButton();


        jLabel1.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        jLabel1.setForeground(new Color(206, 192, 192));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        jLabel2.setForeground(new Color(206, 192, 192));
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Gill Sans Nova", Font.BOLD, 24)); // NOI18N
        jLabel3.setForeground(new Color(206, 192, 192));
        jLabel3.setText("LOGIN");

        txt_username.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        txt_username.setForeground(new Color(206, 192, 192));
        txt_username.setBackground(Color.gray);
        txt_username.setBorder(new LineBorder(Color.BLACK, 1));

        txt_password.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        txt_password.setForeground(new Color(206, 192, 192));
        txt_password.setBackground(Color.gray);
        txt_password.setBorder(new LineBorder(Color.BLACK, 1));


        btn_new.setText("Register");
        btn_new.setForeground(new Color(206, 192, 192));
        btn_new.setBackground(Color.gray);
        btn_new.setBorder(new LineBorder(Color.BLACK, 2));
        btn_new.setVisible(true);

        btn_login.setText("Login");
        btn_login.setForeground(new Color(206, 192, 192));
        btn_login.setBackground(Color.gray);
        btn_login.setBorder(new LineBorder(Color.BLACK, 2));
        btn_login.setVisible(true);
        btn_login.addActionListener(evt -> {
            updateCurser.set(true);
            btn_loginActionPerformed();
        });
        btn_new.addActionListener(this::btn_newActionPerformed);

        add(jLabel1);
        jLabel1.setBounds(20, 100, 200, 20);
        add(jLabel2);
        jLabel2.setBounds(20, 140, 200, 20);
        add(jLabel3);
        jLabel3.setBounds(160, 40, 80, 20);
        add(txt_username);
        txt_username.setBounds(90, 100, 100, 20);
        add(txt_password);
        txt_password.setBounds(90, 140, 100, 20);
        add(btn_login);
        btn_login.setBounds(80, 300, 90, 30);
        add(btn_new);
        btn_new.setBounds(230, 300, 90, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private final JFrame frame1 = new JFrame("Register");
    private final JPanel register = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            BufferedImage img;
            try {
                img = ImageIO.read(Objects.requireNonNull(getClass().getResource("/bk/reg.png")));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            g.drawImage(img, 0,0, 300,300, null);
        }

    };
    private final javax.swing.JTextField txt_password1 = new JTextField();
    private final javax.swing.JTextField txt_username1 = new JTextField();
    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {

        frame1.setResizable(false);
        frame1.setCursor(Cursor.HAND_CURSOR);
        register.setLayout(null);
        register.setBackground(Color.DARK_GRAY);
        register.updateUI();
        frame1.add(register);
        register.setVisible(true);
        register.setBounds(820,390,300,300);
        frame1.setBounds(820, 390, 300, 300);
        frame1.setVisible(true);

        javax.swing.JLabel jLabel12 = new JLabel();
        javax.swing.JLabel jLabel22 = new JLabel();
        javax.swing.JButton btn_register= new JButton();

        txt_username1.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18
        txt_username1.setVisible(true);
        txt_username1.setForeground(new Color(206, 192, 192));
        txt_username1.setBackground(Color.gray);
        txt_username1.setBorder(new LineBorder(Color.BLACK, 1));

        txt_password1.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        txt_password1.setVisible(true);
        txt_password1.setForeground(new Color(206, 192, 192));
        txt_password1.setBackground(Color.gray);
        txt_password1.setBorder(new LineBorder(Color.BLACK, 1));

        btn_register.setText("Register");
        btn_register.setVisible(true);
        btn_register.setForeground(new Color(206, 192, 192));
        btn_register.setBackground(Color.gray);
        btn_register.setBorder(new LineBorder(Color.BLACK, 2));

        JLabel nameorPwdToShort = new JLabel();
        nameorPwdToShort.setForeground(Color.RED);
        nameorPwdToShort.setBackground(Color.green);
        nameorPwdToShort.setFont(new Font("Segoe UI" , Font.PLAIN, 10));
        nameorPwdToShort.setText("Un & Pwd must be at least 4 characters long");
        nameorPwdToShort.setBounds(50, 130 , 200, 20);
        nameorPwdToShort.setVisible(false);
        frame1.add(nameorPwdToShort);

        btn_register.addActionListener(evt1 -> {
            nameorPwdToShort.setVisible(false);
            if(txt_username1.getText().length() > 3 && txt_password1.getText().length() > 3) {
                btn_registerActionPerformed();
            }else {
                nameorPwdToShort.setVisible(true);
            }

        });


        jLabel12.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        jLabel12.setText("Username");
        jLabel12.setForeground(new Color(206, 192, 192));
        jLabel22.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
        jLabel22.setText("Password");
        jLabel22.setForeground(new Color(206, 192, 192));


        jLabel12.setBounds(20, 20, 100, 20);
        jLabel22.setBounds(20, 60,100, 20);


        register.add(jLabel12);
        register.add(jLabel22);

        register.add(txt_username1);
        txt_username1.setBounds(140,20,100,20);
        register.add(txt_password1);
        txt_password1.setBounds(140,60,100,20);


        register.add(btn_register);
        btn_register.setBounds(100,160,100,30);
        frame1.add(register);



    }

    private void btn_registerActionPerformed() {

        SenderObject s = new SenderObject(Instruction.CREATEUSER);
        User l = new User();
        l.setUsername(txt_username1.getText());
        l.setPassword(txt_password1.getText());
        l.setLevel(1);
        l.setXp(0);
        l.setCreatedate();
        s.setUser(l);
        try {
            Editor_Main.getSocket().getOut().writeObject(s);

        } catch (IOException e) {
            e.printStackTrace();
        }
        frame1.dispose();
    }

    public User l = new User();
    private void btn_loginActionPerformed() {//GEN-FIRST:event_btn_loginActionPerformed
        SenderObject s = new SenderObject(Instruction.REQUESTUSER);

        l.setUsername(txt_username.getText());
        l.setPassword(txt_password.getText());
        s.setUser(l);

        try {
            Editor_Main.getSocket().getOut().flush();
            Editor_Main.getSocket().getOut().reset();
            Editor_Main.getSocket().getOut().writeUnshared(s);
        } catch (IOException e) {
            e.printStackTrace();
        }
        User u = null;

        int nigger = 0;
        try {
            SenderObject b = (SenderObject) Editor_Main.getSocket().getIn().readObject();
            if(b.getCode()==69){
                nigger = 69;
                JOptionPane.showMessageDialog(null, "Dieser Benutzer ist bereits angemeldet");
            }else{
                u = b.getUser();
                if(u!=null) {
                    SettingsMgr.init(Editor_Main.getSocket());
                }

            }



        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }


        if(u != null){
            Editor_Main.setLoggedInUser(u);
            frame1.dispose(); //TODO marked for some reason
            menu = new StartMenu();

            menu.StartMenu();
            menu.SeitenMenu();
            parent.dispose();


        }else if (nigger == 0){
            txt_password.setText("");
            txt_username.setText("");
            JOptionPane.showMessageDialog(parent, "Benutzername oder Passwort falsch!");
        }else {
            txt_password.setText("");
            txt_username.setText("");
        }//GEN-LAST:event_btn_loginActionPerformed
    }


    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
